#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=95
boot() {
	[ -e /proc/driver/xtm/dropmcast ] && echo 0 > /proc/driver/xtm/dropmcast
	[ -e /proc/driver/bcmsw/drop_mcast ] && echo 0 > /proc/driver/bcmsw/drop_mcast
	[ -d /tmp/root ] && {
		lock /tmp/.switch2jffs
		firstboot switch2jffs
		lock -u /tmp/.switch2jffs
	}

	# process user commands
	[ -f /etc/rc.local ] && {
		sh /etc/rc.local
	}

	# set leds to normal state
	. /etc/diag.sh
	set_state done
}
